global:
  scrape_interval: 30s
  scrape_timeout: 10s
  evaluation_interval: 1m

rule_files:
  - prometheus/alert.yaml

scrape_configs:
  - job_name: 'monitor'
    static_configs:
      - targets: ['192.168.9.208:9200']

          